# Generated by Django 3.1.2 on 2020-11-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seek_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
