# Generated by Django 3.1.2 on 2020-11-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
