# Generated by Django 3.1.2 on 2020-11-22 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_request',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
