# Generated by Django 3.1.2 on 2020-10-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('blood_group', models.CharField(blank=True, default='', max_length=3)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.BooleanField()),
                ('seek_text', models.TextField()),
                ('date_seek', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
