# Generated by Django 3.1.2 on 2020-10-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_welfare_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
