# Generated by Django 3.1.2 on 2020-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_welfare_api', '0002_auto_20201026_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='slug',
        ),
        migrations.AlterField(
            model_name='user1',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
